# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#To specify the events when you want to run the pipeline
trigger:
- master
#- releases/*

# Trigger for pull request validation
pr:
  - master
  - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

    #To build with a command line or script
    #steps:
# - script: |
#     echo Starting the build
#     mvn package
#   displayName: 'Build with Maven'

# runs a script file that is in your repository
#steps:
# - task: ShellScript@2
#   inputs:
#     scriptPath: 'script.sh'

